# render.yaml
services:
  - type: web
    name: pulsetrack-backend
    runtime: docker
    repo: https://github.com/PulseTrackDev/PulseTrackBackend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
